### ISSUE TITLE
[question] difference between sparv api 2 & 3

### ISSUE THREAD

**Issue by spcsmrf** [spraakbanken/sb-api-doc#6]
What is the difference between https://ws.spraakbanken.gu.se/ws/sparv/v2/ and https://ws.spraakbanken.gu.se/docs/sparv ?

**Comment by anne17** [comment]
https://ws.spraakbanken.gu.se/ws/sparv/v2/ is the adress to Sparv's REST API version 2. https://ws.spraakbanken.gu.se/docs/sparv is the documentation page for the new version (3) of Sparv (which will live at https://ws.spraakbanken.gu.se/ws/sparv/v3/). The main difference between the versions is that the new one will respond with JSON instead of XML. Sparv version 3 has not yet been released and is not fully functional at the moment.

**Comment by anne17** [comment]
Sparv version 3 is now running at https://ws.spraakbanken.gu.se/ws/sparv/v3/ . There are probably quite a few bugs (e.g. file upload is not yet working). We are happy to receive Sparv bug reports via https://github.com/spraakbanken/sparv-backend or sb-sparv@svenska.gu.se.
